title: Linux kurs
description: Linux code
baseurl: "https://alexiandra97.github.io/linux_kurs/"
url: https://alexiandra97.github.io/linux_kurs/


markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
